ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Models/Korisnik.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace StudentskaBanka.Models
{
    public class Korisnik
    {
        [ScaffoldColumn(false)]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Ime")]
        public String ime { get; set; }

        [Required]
        [Display(Name = "Prezime")]
        public String prezime { get; set; }

        [Display(Name = "Matični broj")]
        public String jmbg { get; set; }

        [Display(Name = "Adresa")]
        public String adresa { get; set; }

        [Display(Name = "Broj telefona")]
        public String brTelefona { get; set; }

        [Required]
        [Display(Name = "Email")]
        public String mail { get; set; }

        [Required]
        [Display(Name = "Password")]
        public String password { get; set; }

        public int racunId { get; set; }

        public Korisnik() { }

        public Korisnik(int ID, string ime, string prezime, string jmbg, string adresa, string brTelefona, string mail, 
            string password, int racunId)
        {
            this.ID = ID;
            this.ime = ime;
            this.prezime = prezime;
            this.jmbg = jmbg;
            this.adresa = adresa;
            this.brTelefona = brTelefona;
            this.mail = mail;
            this.password = password;
            this.racunId = racunId;
        }
    }
}

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Controllers/KorisniksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentskaBanka.Models;

namespace StudentskaBanka.Controllers
{
    public class KorisniksController : Controller
    {
        private BankaContext db = new BankaContext();

        // GET: Korisniks
        public ActionResult Index()
        {
            return View(db.Korisnik.ToList());
        }

        // GET: Korisniks/Details/5
        public ActionResult Details()
        {
            if (Session["UserId"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisnik.Find(Session["UserId"]);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // GET: Korisniks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Korisniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ime,prezime,jmbg,adresa,brTelefona,mail,password,racunId")] Korisnik korisnik)
        {
            
            if (ModelState.IsValid)
            {
                db.Korisnik.Add(korisnik);
                Racun racun = new Racun(0, false);
                db.Racun.Add(racun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(korisnik);
        }

        // GET: Korisniks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisnik.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ime,prezime,jmbg,adresa,brTelefona,mail,password,racunId")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(korisnik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(korisnik);
        }

        // GET: Korisniks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Korisnik korisnik = db.Korisnik.Find(id);
            if (korisnik == null)
            {
                return HttpNotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Korisnik korisnik = db.Korisnik.Find(id);
            db.Korisnik.Remove(korisnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Controllers/RacunsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentskaBanka.Models;

namespace StudentskaBanka.Controllers
{
    public class RacunsController : Controller
    {
        private BankaContext db = new BankaContext();

        // GET: Racuns
        public ActionResult Index()
        {
            return View(db.Racun.ToList());
        }

        // GET: Racuns/Details/5
        public ActionResult Details()
        {
            if (Session["racunId"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Racun racun = db.Racun.Find(Session["racunId"]);
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // GET: Racuns/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Racuns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,stanje,blokiran")] Racun racun)
        {
            if (ModelState.IsValid)
            {
                db.Racun.Add(racun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(racun);
        }

        // GET: Racuns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Racun racun = db.Racun.Find(id);
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // POST: Racuns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,stanje,blokiran")] Racun racun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(racun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(racun);
        }

        // GET: Racuns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Racun racun = db.Racun.Find(id);
            if (racun == null)
            {
                return HttpNotFound();
            }
            return View(racun);
        }

        // POST: Racuns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Racun racun = db.Racun.Find(id);
            db.Racun.Remove(racun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Controllers/TransakcijasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentskaBanka.Models;

namespace StudentskaBanka.Controllers
{
    public class TransakcijasController : Controller
    {
        private BankaContext db = new BankaContext();

        // GET: Transakcijas
        public ActionResult Index()
        {
            return View(db.Transakcija.ToList());
        }

        // GET: Transakcijas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transakcija transakcija = db.Transakcija.Find(id);
            if (transakcija == null)
            {
                return HttpNotFound();
            }
            return View(transakcija);
        }

        // GET: Transakcijas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Transakcijas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,posiljalacId,primalacId,vrijeme,iznos")] Transakcija transakcija)
        {
            if (ModelState.IsValid)
            {
                db.Transakcija.Add(transakcija);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(transakcija);
        }

        // GET: Transakcijas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transakcija transakcija = db.Transakcija.Find(id);
            if (transakcija == null)
            {
                return HttpNotFound();
            }
            return View(transakcija);
        }

        // POST: Transakcijas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,posiljalacId,primalacId,vrijeme,iznos")] Transakcija transakcija)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transakcija).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(transakcija);
        }

        // GET: Transakcijas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transakcija transakcija = db.Transakcija.Find(id);
            if (transakcija == null)
            {
                return HttpNotFound();
            }
            return View(transakcija);
        }

        // POST: Transakcijas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transakcija transakcija = db.Transakcija.Find(id);
            db.Transakcija.Remove(transakcija);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Views/Korisniks/Create.cshtml
@model StudentskaBanka.Models.Korisnik

@{
    ViewBag.Title = "Create";
}

<style>
    body {
        background-image: url(https://images.unsplash.com/photo-1500316124030-4cffa46f10f0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7c3583c9e0a39944ac510280a55bcc0b&auto=format&fit=crop&w=1500&q=80);
        color: azure;
        font-family: 'DejaVu Sans';
    }

    h2 {
        color:lightgoldenrodyellow;
        font-family:'DejaVu Sans';
    }
    
</style>

<h2>Registracija novog korisnika</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal kontejner">
        <h4>Korisnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jmbg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jmbg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jmbg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brTelefona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.brTelefona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.brTelefona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.racunId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.racunId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.racunId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registruj se" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Views/Korisniks/Delete.cshtml
@model StudentskaBanka.Models.Korisnik

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Korisnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jmbg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jmbg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brTelefona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brTelefona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.racunId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.racunId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Views/Korisniks/Details.cshtml
@model StudentskaBanka.Models.Korisnik

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Korisnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jmbg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jmbg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brTelefona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brTelefona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Uredi profil", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Otvori račun", "Details", "Racuns") |
    @Html.ActionLink("Nova transakcija", "Create", "Transakcijas"))

</p>

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Views/Korisniks/Edit.cshtml
@model StudentskaBanka.Models.Korisnik

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Korisnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jmbg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jmbg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jmbg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brTelefona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.brTelefona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.brTelefona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjekatStudentskaBanka-ASP.NET/StudentskaBanka/StudentskaBanka/Views/Korisniks/Index.cshtml
@model IEnumerable<StudentskaBanka.Models.Korisnik>

@{
    ViewBag.Title = "Index";
}

<style>
    body {
        background-image: url(https://images.unsplash.com/photo-1500316124030-4cffa46f10f0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7c3583c9e0a39944ac510280a55bcc0b&auto=format&fit=crop&w=1500&q=80);
        color: lightgoldenrodyellow;
        font-family:'DejaVu Sans';
    }
</style>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <a href="~/Views/Korisniks/Index.cshtml">~/Views/Korisniks/Index.cshtml</a>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.jmbg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.adresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.brTelefona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.mail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.racunId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.jmbg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.adresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brTelefona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.racunId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>